<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AUCTION</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- EF Core + PostgreSQL -->
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />

    <!-- JWT Auth -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />

    <!-- MassTransit + RabbitMQ -->
    <PackageReference Include="MassTransit" Version="8.2.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />

    <!-- Redis -->
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />

    <!-- SignalR -->
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />

    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="xunit" Version="2.9.3" />

    <!-- Shared contracts (reference your Messaging.Contracts project) -->
    <!-- <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" /> -->
  </ItemGroup>

</Project>
