FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /App
COPY *.csproj .
COPY . .
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 
WORKDIR /App
COPY --from=build /publish .
ENTRYPOINT [ "dotnet","Verify.dll" ]